name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install libasound-dev libportaudio2 libportaudiocpp0 portaudio19-dev -y
      - name: Lint with flake8
        run: |
          pip install flake8 pytest
          flake8 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest
